version: '3.1'

services:
    db:
        image: mysql:8.0.25
        container_name: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: "${MYSQL_PASSWORD}"
            MYSQL_DATABASE: users_db
        networks:
            - backend
        volumes:
            - ./init.sql:/docker-entrypoint-initdb.d/init.sql

networks:
    backend:
        driver: bridge