version: '3.1'

services:
  users-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: users-api
    restart: on-failure
    ports:
      - "8081:8081"
    environment:
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: root
      MYSQL_ADDRESS: mysql:3306
      MYSQL_SCHEMA: users_db
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0.25
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: users_db
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

networks: 
  default:
    external: true
    name: shared-backend