CREATE DATABASE IF NOT EXISTS users_db;
USE users_db;
CREATE TABLE users (
id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
first_name NVARCHAR(45) DEFAULT '',
last_name NVARCHAR(45) DEFAULT '',
email VARCHAR(100) UNIQUE NOT NULL,
date_created DATETIME NOT NULL,
status VARCHAR(45) NOT NULL,
password VARCHAR(45) NOT NULL
);