CREATE DATABASE IF NOT EXISTS users_db;
USE users_db;
CREATE TABLE users (
id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
first_name NVARCHAR(100) NOT NULL,
last_name NVARCHAR(100) NOT NULL,
email NVARCHAR(100) NOT NULL,
date_created NVARCHAR(100) NOT NULL
);